### ISSUE TITLE
please host this static site on github pages

### ISSUE THREAD

**Issue by itsvinayak** [thecodercoder/fem-easybank#4]

**Comment by jonwk** [comment]
I have worked on hosting this page on GitHub pages, check out the live demo [here](https://jonwk.github.io/Easy-Bank-Landing-Page/) I also noticed other people hosting on GitHub pages, for example check out the implementation from @irisdiakoumi [here](https://irisdiakoumi.github.io/easybank/). Hope this helps 😁
